# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/joseph-caterine-578a73268/"

[[social.params]]
icon = "brand-linkedin"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/gam32bit"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/jwcat757"

[social.params]
icon = "brand-twitter"
